I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 788, in script
    if b_back == 1:
  File "game/script.rpy", line 788, in <module>
    if b_back == 1:
NameError: name 'b_back' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 788, in script
    if b_back == 1:
  File "/Volumes/renpy-8.3.2-sdk/renpy-8.3.2-sdk/renpy/ast.py", line 1843, in execute
    if renpy.python.py_eval(condition):
  File "/Volumes/renpy-8.3.2-sdk/renpy-8.3.2-sdk/renpy/python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Volumes/renpy-8.3.2-sdk/renpy-8.3.2-sdk/renpy/python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 788, in <module>
    if b_back == 1:
NameError: name 'b_back' is not defined

macOS-15.1.1-arm64-arm-64bit arm64
Ren'Py 8.3.2.24090902
 Beta
Sat Dec 14 15:00:17 2024
