I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 279, in script
    dance_leader "안녕, 모두들! 우리 사진 동아리에 온 걸 환영해. 나는 동아리 장이고, 앞으로 잘 부탁할게!"
Exception: Sayer 'dance_leader' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 279, in script
    dance_leader "안녕, 모두들! 우리 사진 동아리에 온 걸 환영해. 나는 동아리 장이고, 앞으로 잘 부탁할게!"
  File "/Volumes/renpy-8.3.2-sdk/renpy-8.3.2-sdk/renpy/ast.py", line 2573, in execute
    Say.execute(self)
  File "/Volumes/renpy-8.3.2-sdk/renpy-8.3.2-sdk/renpy/ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Volumes/renpy-8.3.2-sdk/renpy-8.3.2-sdk/renpy/ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'dance_leader' is not defined.

macOS-15.1-arm64-arm-64bit arm64
Ren'Py 8.3.2.24090902
 Beta
Tue Nov 19 14:32:12 2024
